# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-20 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='url_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
