# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-26 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180320_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='url_desc',
        ),
    ]
