# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-06 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_news_url_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('gpsies', models.CharField(blank=True, max_length=255, null=True)),
                ('ranking', models.FloatField(default=0)),
                ('level', models.PositiveIntegerField()),
                ('season', models.CharField(blank=True, max_length=255, null=True)),
                ('bike_type', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.DurationField(default=0)),
                ('distance', models.PositiveSmallIntegerField()),
                ('photo_google', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.ManyToManyField(blank=True, to='news.Comments')),
            ],
            options={
                'ordering': ['level'],
            },
        ),
    ]
