# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-27 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0002_events_email_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultevent',
            name='dnf',
            field=models.BooleanField(default=False),
        ),
    ]
