# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-31 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0003_resultevent_dnf'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('distance', models.PositiveSmallIntegerField(default=0, help_text=b'\xd0\x94\xd0\xbe\xd0\xb2\xd0\xb6\xd0\xb8\xd0\xbd\xd0\xb0 \xd0\xbc\xd0\xb0\xd1\x80\xd1\x88\xd1\x80\xd1\x83\xd1\x82\xd1\x83, \xd0\xba\xd1\x96\xd0\xbb\xd0\xbe\xd0\xbc\xd0\xb5\xd1\x82\xd1\x80\xd0\xb8')),
                ('description', models.TextField(blank=True, help_text=b'\xd0\x9e\xd0\xbf\xd0\xb8\xd1\x81 \xd0\xb4\xd0\xb8\xd1\x81\xd1\x82\xd0\xb0\xd0\xbd\xd1\x86\xd1\x96\xd1\x97')),
            ],
            options={
                'ordering': ['event', 'distance', 'name'],
            },
        ),
        migrations.AddField(
            model_name='events',
            name='cup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventdistance',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_calendar.Events'),
        ),
        migrations.AddField(
            model_name='regevent',
            name='distance_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_calendar.EventDistance'),
        ),
    ]
