# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-24 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0004_auto_20181031_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckPointEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_time', models.DateTimeField(blank=True, null=True)),
                ('hash', models.CharField(blank=True, max_length=255)),
                ('checksum', models.CharField(blank=True, max_length=255)),
                ('number', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['result_event', 'check_time'],
            },
        ),
        migrations.CreateModel(
            name='EventDistCheckPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('secret_hash', models.CharField(max_length=255)),
                ('km', models.PositiveSmallIntegerField(default=0, help_text=b'\xd0\x9a\xd1\x96\xd0\xbb\xd0\xbe\xd0\xbc\xd0\xb5\xd1\x82\xd1\x80 \xd0\xbd\xd0\xb0 \xd1\x8f\xd0\xba\xd0\xbe\xd0\xbc\xd1\x83 \xd1\x80\xd0\xbe\xd0\xb7\xd1\x82\xd0\xb0\xd1\x88\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb5 \xd0\x9a\xd0\x9f')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9)),
                ('photo', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text=b'\xd0\x9e\xd0\xbf\xd0\xb8\xd1\x81 \xd0\xbb\xd0\xbe\xd0\xba\xd0\xb0\xd1\x86\xd1\x96\xd1\x97')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='eventdistance',
            name='gps_track',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eventdistance',
            name='kp_count',
            field=models.IntegerField(default=0, help_text=b'\xd0\x9a\xd1\x96\xd0\xbb\xd1\x8c\xd0\xba\xd1\x96\xd1\x81\xd1\x82\xd1\x8c \xd0\x9a\xd0\x9f'),
        ),
        migrations.AddField(
            model_name='events',
            name='checkpoint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resultevent',
            name='checkpoint',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultevent',
            name='penalty',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventdistcheckpoint',
            name='event_distance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_calendar.EventDistance'),
        ),
        migrations.AddField(
            model_name='checkpointevent',
            name='result_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_calendar.ResultEvent'),
        ),
    ]
