# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-24 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0005_auto_20190724_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='photo_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='events',
            name='uat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='video_url',
            field=models.TextField(blank=True),
        ),
    ]
