# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-26 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0006_auto_20190724_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointevent',
            name='data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='events',
            name='chkhash',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
